### PR TITLE
Feature/empowerplan initial step 3

### PR DESCRIPTION
**Pull request by bmlancien**
@nesnoj I added a wizard view that is semi-functional (it works until step 3). Because of this, the design is not 100% like it should be, but quite close.

I also added pictures taken from the mockups for EmPowerPlan, one for the sidebar and one of the main view. I was not able to make the main view only visible for step 3, though, so now it is visible on all steps and therefore the map is hidden. Is it ok this way?

### CODE REVIEW

**Review by nesnoj — CHANGES_REQUESTED** [review]
Thx @bmlancien for the quick proposal, LGTM!
But yes, I need the scenario to be visible in the 3rd step only as I'd like to smoothly go through all the steps:
1. Herausforderungen - some dummy gfx + text on white main view (as in 3)
2. Region heute - like in the current app
3. Szenarien - new main view
4. Einstellungen - like in the current app
5. Ergebnisse - like in the current app

Also, I'll send you some new scenario names and captions via mail I'd like you to update.

@henhuy, could you help out with the show & hide stuff?

**Comment by nesnoj** [comment]
Thx for the fix @henhuy!
However, the process stops at no 3 as the weiter button is disabled. Can it just be enabled again or is there more that needs to be done to make all steps accessible?

**Comment by henhuy** [comment]
This needs a little bit more work. As the 3 steps are hardcoded. Are the other tab contents ready?

**Comment by bmlancien** [comment]
@nesnoj I updated the images for the scenario view. 

> Herausforderungen - some dummy gfx + text on white main view (as in 3)

What should I/we add to the sidebar and main view? Right now the main view is still a map for step 1.

@henhuy Thanks for helping me with the map/main view! Do you know how to remove the option/layer boxes from step 3?

**Comment by nesnoj** [comment]
> This needs a little bit more work. As the 3 steps are hardcoded. Are the other tab contents ready? 

The other steps (4+5) are the same as in DP for now

**Comment by nesnoj** [comment]
> @nesnoj I updated the images for the scenario view. 
> 
> > Herausforderungen - some dummy gfx + text on white main view (as in 3)
> 
> What should I/we add to the sidebar and main view? Right now the main view is still a map for step 1.

Just white as in 3.
Left panel empty and some lorem ipsum in the main. If I can make it timewise I'll send you some ideal for the content.

**Comment by bmlancien** [comment]
> Left panel empty and some lorem ipsum in the main.

The left panel on step 1 is now empty. The map is still there, though. I can't change it on my own...

**Comment by henhuy** [comment]
I just updated tab steps and integrated challenges and scenario panels (both empty at the moment).
Map is hidden completely in step 5 now.

**Comment by henhuy** [comment]
Sorry. Now it should look better.
The main view for first step is not yet present.
Once it is designed, i can turn off map and show content instead (like in step 3).

**Comment by bmlancien** [comment]
@henhuy There's no content so far for step 1, so I think you can turn off the map.

**Comment by nesnoj** [comment]
Do you have time today to tackle the last adjustments from above?
@henhuy Turn off the map&legend in step (1)?
@bmlancien Add dummy img+text for this step?

**Comment by henhuy** [comment]
I think i have a short time frame later to fix this quickly

**Comment by henhuy** [comment]
> Hi @henhuy Sorry for removing the view toggle tabs, but we will need it on step 5 (results)... But this time it should be below the wizard, like it was in Digiplan before:
> 
> chrome-capture-2023-10-16
> 
> This is the PR from when we moved the tabs from this position to the top right next to the steps, maybe that can help: #215

Should work again!

**Comment by nesnoj** [comment]
> Should work again!

Thx!

**Comment by bmlancien** [comment]
@nesnoj I implemented the changes. What do you think?

**Comment by nesnoj** [comment]
> @nesnoj I implemented the changes. What do you think?

LGTM, thx a lot! :pray:

**Comment by nesnoj** [comment]
Created new codebase for EPP and migrated changes there: https://github.com/empowerplan/epp-app/pull/1

**Pull request closed without merging**
