### PR TITLE
Bug/fix translation

### PR DESCRIPTION
**Pull request by josihoppe**
translated all the english texts from the list and others that I found

### CODE REVIEW

**Comment by josihoppe** [comment]
could not find a way to translate the icon for changing the layers of the map (default / satelite)

**Comment by nesnoj** [comment]
Ok @josihoppe, I'm done for now, please insert the texts for the right layers starting from settlements as described in RC.

**Comment by josihoppe** [comment]
@nesnoj I added the layer descriptions but couldn't find some for the layers "Soil Quality High", "Soil Quality Low" and "Straßen und Bahnverkehr (500 m Puffer)"

**Review by nesnoj — APPROVED** [review]
I think we're done here, thanks for finding and fixing!

**Pull request merged**
